version: '3.8'
name: backend-drf

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend-drf-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    networks:
      - backend-drf-networks
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_data:

networks:
  backend-drf-networks:
